Build WorkloadTest.Internal nuget only when building wasm
This avoids trying to build the target for unrelated linux/sourcebuild
jobs.

`/__w/1/s/artifacts/sb/src/src/tasks/WorkloadBuildTasks/InstallWorkloadFromArtifacts.cs(61,38): error CS8795: Partial method 'InstallWorkloadFromArtifacts.bandVersionRegex()' must have an implementation part because it has accessibility modifiers. [/__w/1/s/artifacts/sb/src/src/tasks/WorkloadBuildTasks/WorkloadBuildTasks.csproj::TargetFramework=net8.0]`